# OpooPress site configuration

# ----------------------- #
#      Main               #
# ----------------------- #

# The title of your site
title: My OpooPress Site

# The subtitle of your site
subtitle: Just another OpooPress site

# author, your name
author: Your Name

# The description of your site. Use as web page description meta value normaly.
description: "OpooPress Framework is a java based static site generator."

# The keywords of your site.
keywords: "OpooPress, Static site generator, Blog"

# The locale(region and language) of your site.
# check java.util.Locale at http://docs.oracle.com/javase/7/docs/api/java/util/Locale.html
locale: en_US


# ----------------------- #
#      URL                #
# ----------------------- #

# The URL of your site.
url: http://yoursite.com

# The root directory of your site.
# If your site is put in a subdirectory such as 'http://yoursite.com/blogs', set root to '/blogs'
# No '/' at the end of root.
# Default value is ''.
# root: ''

# Encode URL.
#
# Default value is false
# url_encode: false

# Decode URL
#
# Default value is false
# url_decode: false

# The permalink format of posts.
# Supported variables: All front-matter meta properties, and ${year}, ${month}, ${day}, ${hour},${minute}, ${second},
# ${name}, ${pathToFile}, ${fileName} etc.
# Default value is '/article/${year}/${month}/${name}.html'.
# permalink_post: '/article/${year}/${month}/${name}.html'

# The permalink format of other LAYOUT.
# Supported variables: All front-matter meta properties, and ${year}, ${month}, ${day}, ${hour},${minute}, ${second},
# ${name}, ${pathToFile}, ${fileName} etc.
# No default value.
# permalink_<LAYOUT>: <YOUR PERMALINK FORMAT>
# Sample: permalink for custom layout 'doc':
# permalink_doc: '/docs/${version}/${name}.html'


# ----------------------- #
#   Directory             #
# ----------------------- #
# default layout
#(.)
# |
# +- pom.xml
# |
# +- config.yml
# |
# +- assets/
# |
# +- pages/
# |
# +- posts/
# |
# +- plugins/
# |
# +- themes/
#     |
#     +- default/
#     |    |
#     |    +- theme.yml
#     |    |
#     |    +- ...
#     |
#     +- another-theme/

# Asset folders, these folders are where you can put your static resources, such as images, css files, javascript files.
# Default value is [assets].
# asset_dirs: [assets]

# Source folders, these folders are where you can put your content.
# Default value is [pages, posts].
# source_dirs: [pages, posts]

# Plugin folder, this folder is where you can put plugin jar files.
# Default value is 'plugins'.
# plugin_dir: plugins

# Destination folder, this folder is where the generated files will be.
# Default value is 'target/public'
# dest_dir: target/public

# Working directory.
# Default value is 'target/work'
# work_dir: target/work


# ----------------------- #
#    Writing              #
# ----------------------- #

# The full path and filename of the new post.
# Commonly, we also need define property 'new_post_template' in theme configuration file(theme.yml).
#
# Supported variables: ${year}, ${month}, ${day}, ${hour}, ${minute}, ${second}, ${name}, ${title}, ${date}, ${format}
# The default value of format is 'markdown'.
#
# The default value of new_post is 'posts/${year}-${month}-${day}-${name}.${format}'.
# new_post: 'posts/${year}-${month}-${day}-${name}.${format}'

# The full path and filename of the new page.
# Commonly, we also need define property 'new_page_template' in theme configuration file(theme.yml).
#
# Supported variables: ${year}, ${month}, ${day}, ${hour}, ${minute}, ${second}, ${name}, ${title}, ${date}, ${format}
# The default value of format is 'markdown'.
#
# The default value of new_post is 'pages/${name}.${format}'
# new_page: 'pages/${name}.${format}'

# The new file full path and filename for other custom layout..
# new_<LAYOUT>: <FORMAT>
# Commonly, we also need define property 'new_<LAYOUT>_template' in theme configuration file(theme.yml).
#
# Supported variables: ${year}, ${month}, ${day}, ${hour}, ${minute}, ${second}, ${name}, ${title}, ${date}, ${format}
# The default value of format is 'markdown'.
#
# Sample: new_doc: 'pages/docs/${name}.md'

# Transform title into proper title case.
# Default value is false.
# titlecase: false

# Excerpt separator.
# Default value is '<!--more-->'
# excerpt_separator: '<!--more-->'


# ----------------------- #
# Pagination & Limitation #
# ----------------------- #

# The amount of the posts displayed in index page. Default value is 10.
# paginate: 10

# Recent posts limit. Default value is 5.
# For blog-aware website only.
# recent_posts: 5

# Related post count of a single post. Default value is 5.
# For blog-aware website only.
# related_posts: 5


# ----------------------- #
#   Date/Time format      #
# ----------------------- #

# The default value of date format is 'yyyy-MM-dd'(ref java.util.Date).
# The special value 'ordinal' equals to 'MMM d yyyy', eg. 'SEP 15 2013'
# http://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html.
# date_format: "ordinal"

# Time format. http://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html.
# time_format: 'HH:mm:ss'


# ----------------------- #
#   Deployment Settings   #
# ----------------------- #

# Deployment servers info.
# You can deploy OpooPress to multiple servers/repositories.
# ref http://maven.apache.org/pom.html#Distribution_Management
#
# deploy:
# - {id: server1, url: 'scp://server1.com/var/www/html'}
# - {id: server2, url: 'scp://server2.com/var/www/html'}
# - {id: local, url: 'file://D:/www'}
